sudo: required

language: node_js
node_js:
  - "stable"

services:
  - docker

before_install:
  - docker build -t kevinchu/first-blog-mern .
  - docker run -d -p 127.0.0.1:4000:3000 kevinchu/first-blog-mern
  - docker ps -a

script:
  - npm run lint
  - npm run test
